<a href="https://colab.research.google.com/github/Malappa9604/basic/blob/main/basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 10
name = "Malu"
price = 100.5
print(type(price))

<class 'float'>


In [ ]:
a = 10 int
b = 3.14 float
c = "hello" string
d = True boolean_
e = None null

SyntaxError: invalid syntax (ipython-input-957135539.py, line 1)

In [ ]:
 def fun(name):
  print("Hello", name)

  func("vignesh")

  def add(a,b):
    return a + b

  result = add(5,3)
  print(result)



In [ ]:
 # call back funcation
 def call-back():
  print("callback funcation")

  def mainfuncation(callback):
    print("main funcation started")
    callback()
    print("main funcation ended")

    mainfuncation(call-back)


SyntaxError: expected '(' (ipython-input-472915786.py, line 2)

In [ ]:
numbers = [1,2,3,4]

square = []
for n in numbers:
    square.append(n*n)
print(square)

# map with this funcation
def square(x):
    return x*x
    numbers = [1,2,3,4]
    square = list(map(square, numbers))
    print(square)

    # map with this funcation
    # def square(x):
    #   return x*x
    # numbers = [1,2,3,4]
    # result = list(map(square,numbers))

    # map with lambda
    numbers = [1,2,3,4]
    square = list(map(lambda x: x*x, numbers))
    print(square)


[1, 4, 9, 16]


In [ ]:
numbers = [1,2,3,4,5,6]

evens = []
for n in numbers:
    if n % 2 == 0:
        evens.append(n)
print(evens)

# method with filter
def is_even(x):
    return x % 2 == 0
numbers = [1,2,3,4,5,6]
result = list(filter(is_even, numbers))
print(result)


numbers = [1,2,3,4,5,6]
result = list(filter(lambda x: x % 2 == 0, numbers))
print(result)

[2, 4, 6]
[2, 4, 6]
[2, 4, 6]


In [ ]:
numbers = [1,2,3,4]

total = 0
for n in numbers:
    total += n
print(total)

# with reduce

from functools import reduce
def add(x,y):
    return x + y
numbers = [1,2,3,4]
result = reduce(add, numbers)


# with lambda
numbers = [1,2,3,4]
result = reduce(lambda x,y: x + y, numbers)
print(result)

10
10


In [ ]:
# numpy and basics
import numpy as np

lst = [1,2,3]
print(lst*2)
arr = np.array(lst)
print(arr*2)





[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

 # array properties (basic manipulation)

print(arr.ndim)  #dimension
print(arr.shape) #shape
print(arr.size)  # size
print(arr.dtype)  # datatype

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
1
(4,)
4
int64


In [ ]:
arr = np.array([1,2,3,4,5,6])

reshaped = arr.reshape(2,3)
print(reshaped)

# flatten

flat = reshaped.flatten()
print(flat)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
